name: linux repositories

on:
  push:
    tags:
      - "repos-rc*"

# TODO move this to releases.yml including prerelease skipping checks

jobs:
  repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get package artifacts
        uses: i3h/download-release-asset@v1
        with:
          owner: cli
          repo: cli
          tag: latest
          file: .*.deb
      - name: install reprepro
        run: sudo apt-get install -y reprepro
      - name: set up gpg
        run: |
          echo "Importing pubkey..."
          cat script/pubkey.asc | gpg --import --no-tty --batch --yes
          echo "Importing seckey..."
          echo ${{secrets.GPG_KEY}} | base64 -d | gpg --import --no-tty --batch --yes
          #echo "Listing public keys..."
          #gpg --list-keys --with-keygrip
          #echo "Listing secret keys..."
          #gpg --list-secret-keys
          echo "Resetting gpg-agent and ingesting passphrase"
          echo "allow-preset-passphrase" > ~/.gnupg/gpg-agent.conf
          gpg-connect-agent RELOADAGENT /bye
          echo ${{secrets.GPG_PASSPHRASE}} | /usr/lib/gnupg2/gpg-preset-passphrase --preset 867DAD5051270B843EF54F6186FA10E3A1D22DC5
      - name: run reprepro
        run: |
          mkdir upload
          for file in *.deb ; do /usr/bin/reprepro --confdir="+b/script" includedeb stable $file ; done
      - name: "Select repo artifacts"
        # Select only final repo artifacts
        # (this makes reprepro runs stateless)
        run: cp -a dists/ pool/ upload/
      - name: Checkout pages site
        if: "!contains(github.ref, '-')" # skip prereleases
        uses: actions/checkout@v2
        with:
          repository: github/cli.github.com
          path: site
          fetch-depth: 0
          token: ${{secrets.SITE_GITHUB_TOKEN}}
      - name: add files to site
        run: cp -aR upload/* site/packages/
      - name: publish site
        env:
          GIT_COMMITTER_NAME: cli automation
          GIT_AUTHOR_NAME: cli automation
          GIT_COMMITTER_EMAIL: noreply@github.com
          GIT_AUTHOR_EMAIL: noreply@github.com
        run: |
          git -C site add packages
          git -C site commit -m"${GITHUB_REF} packages"
          git -C site push
